name: dl-pytorch-openlab
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - jupyter
  - notebook
  - nbformat
  - nbclient
  - tqdm
  - pip
